### PR TITLE
Add support for finding elements via xpath.

### PR DESCRIPTION
**Pull request by sparhami**

### CODE REVIEW

**Review by cvializ — COMMENTED** [review]
I'm curious why you want to expand the API to accept XPath selectors. Is there a need that this solves better than plain CSS selectors? I'm inclined to keep the API small and to allow few options for accomplishing a goal, that way it takes less time to implement new `FunctionalTestController` implementations should the need arise

**Comment by sparhami** [comment]
There are a lot of things that xpath can do that CSS selectors cannot. For example, if I have DOM like:

```html
<div>
  <div></div>
  <div class="foo"></div>
  <div class="foo"></div>
  <div></div>
</div>
```

There is no way in CSS to target the nth div with class of 'foo'. Being able to target this directly is important because it may not exist yet due to the async nature of things (e.g. the classes can be added after the point you want to find them). With xpath, you can do:

`//div[contains(@class, "foo")][${n}]`

I need this for carousel to find the nth slide. The parent container has things that are not slides in it in addition to the slides, so I can't just use `nth-child`. One case this is especially useful is if I want to wait for a certain number of slides to do layout.

With xpath, I can do `(//amp-carousel//amp-img[contains(@class, "i-amphtml-layout")])[5]` to make sure there are 5 slides with `<amp-img>`s that have laid out. Since the runtime does layout in passes, the first time `i-amphtml-layout` appears, there may not be all 5. Note that xpath is also powerful here in that it lets you look for for the amp-imgs across different subtrees. This is important because they don't actually have a common parent in the example I am working on (so there is no way to write a nth child for this, even if they all appeared at the same time).

**Comment by cvializ** [comment]
I feel like XPath can be very expressive, but that expressiveness comes at the cost of complexity that other contributors, including new contributors, would need to digest in order to understand the test. I am hoping for these e2e tests to be written optimizing for approachability, and I feel like adding XPath queries would put us farther from that goal rather than closer. 

Multiple CSS selectors should be able to accomplish this, but in more lines.

```js
// Make sure there are 5 amp-imgs that have laid out
const ampCarousel = await controller.findElement('amp-carousel');
const imgsWithLayout = await controller.findElementsFromElement(
    ampCarousel, 'amp-img.i-amphtml-layout');
await expect(imgsWithLayout).to.have.length(5);

// Select the second slide with class foo
const ampCarousel = await controller.findElement('amp-carousel');
const foos = await controller.findElementsFromElement(
    ampCarousel, 'div.foo');
await expect(foos[1]).to.be.defined;
```

If there is a use-case where that is absolutely too verbose, I would support XPath selectors being included in our tests.

**Comment by sparhami** [comment]
> const imgsWithLayout = await controller.findElementsFromElement(
    ampCarousel, 'amp-img.i-amphtml-layout');

I'm assuming this is similar to `findElements`, just scoped to a subtree (doesn't seem to be implemented yet). This won't work for the case where the elements matching the selector are not present at the same time. The ControllerPromise for `controller.findElementsFromElement(
    ampCarousel, 'amp-img.i-amphtml-layout');` will resolve as soon as you have a single element matching the selector.

I created a branch with a sample HTML file where you need xpath and a test showing the xpath working and the CSS selector failing: https://github.com/cvializ/ampft-example/compare/master...sparhami:xpath-example

The HTML to illustrate the issue is:

```html
<body>
  <amp-carousel>
    <div></div>
    <div>
      <amp-img></amp-img>
    </div>
    <div>
      <amp-img></amp-img>
    </div>
    <div>
      <amp-img></amp-img>
    </div>
    <div>
      <amp-img></amp-img>
    </div>
    <div>
      <amp-img></amp-img>
    </div>
    <div></div>
  </amp-carousel>

   <script>
    const allImgs = document.querySelectorAll('amp-img');
    let i = 0;
    for (let i = 0; i < 5; i++) {
      setTimeout(() => {
        allImgs[i].className = 'i-amphtml-layout';
      }, 200 * i);
    }
  </script>
</body>
```

**Comment by cvializ** [comment]
> doesn't seem to be implemented yet

If you `git pull` it'll be there. I'll start using PRs and cc-ing you on them so you'll see when there are updates to the repo.

Ok I can see your point now. I believe we could implement a solution for making sure `findElements` and `length` interact to wait until there are the expected number of elements, but if it's already implemented on the XPath layer we should it.

I think the standard of commenting lines with XPath queries will need to be higher than it is for CSS selectors.

**Comment by sparhami** [comment]
I added a function comment to tell people to use the CSS version instead, and to leave a comment for their xpath query. I think since xpath queries are more verbose to begin with, people will avoid them.

Perhaps a lint requiring /*OK*/ would help further restrict usage to where it is really necessary.

**Comment by cvializ** [comment]
I like that idea, thanks a lot. And thanks for opening the PR! I'll merge it now

**Pull request merged**
